tasks:
  - init: |
      sudo apt update -y && sudo apt upgrade -y && sudo autoremove -y && sudo apt install -y protobuf-compiler
      npm install -g wasm-pack
      rustup default nightly
      rustup component add clippy rustfmt --toolchain nightly
      rustup target add wasm32-unknown-unknown wasm32-wasi --toolchain nightly 
      cargo install trunk wasm-bindgen-cli
    command: trunk serve