version: "4"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - /config:/config
      - /data:/data

volumes:
  config:
  data: