name: Docker

on:
  pull_request:
    branches: [ main, master ]
  push:
    branches-ignore: [ "beta*", "dev*", "next*" ]
    tags: [ "nightly*",  "v*.*.*" ]
  release:
      types: [published]
  schedule:
    - cron: "30 9 * * *" # 9:30am UTC
  workflow_dispatch:

env:
  IMAGE_TAG: latest


jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker buildx build --tag ${{ env.IMAGE_NAME }} .
  publish:
    needs: build
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}
    steps:
    - uses: actions/checkout@v3
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        dockerfile: Dockerfile
        name: ${{ env.IMAGE_NAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        snapshot: true
        username: ${{ secrets.DOCKERHUB_USERNAME }}
